	.ORIG x5000

	.STRINGZ "* * * * * * * * * * * * * * * * * * * * * * *"
	.STRINGZ "*                                         U *"
	.STRINGZ "*         * * * *   * * *   * * * *         *"
	.STRINGZ "*         *     *   *   *   *     *         *"
	.STRINGZ "*         *     *   *   *   *     *         *"
	.STRINGZ "*   * * * * * * *   * * *   * * * * * * *   *"
	.STRINGZ "*   *     *                       *     *   *"
	.STRINGZ "*   *     *   * * * * U * * * *   *     *   *"
	.STRINGZ "*   * * * *   * * * *   * * * *   * * * *   *"
	.STRINGZ "*                                           *"
	.STRINGZ "*   * * * * * * * * * U * * * * * * * * *   *"
	.STRINGZ "*   *               *   *               *   *"
	.STRINGZ "*   * * * * * * * * * U * * * * * * * * *   *"
	.STRINGZ "*                                           *"
	.STRINGZ "*   * * * *   * * * *   * * * *   * * * *   *"
	.STRINGZ "*   *     *   * * * * U * * * *   *     *   *"
	.STRINGZ "*   *     *     o                 *     *   *"
	.STRINGZ "*   * * * * * * *   * * *   * * * * * * *   *"
	.STRINGZ "*         *     *   *   *   *     *         *"
	.STRINGZ "*         *     *   *   *   *     *         *"
	.STRINGZ "*         * * * *   * * *   * * * *         *"
	.STRINGZ "* U                                         *"
	.STRINGZ "* * * * * * * * * * * * * * * * * * * * * * *"

	.STRINGZ "* * * * * * * * * * * * * * * * * * * * * * *"
	.STRINGZ "*                                       U   *"
	.STRINGZ "*         * * * *   * * *   * * * *         *"
	.STRINGZ "*         *     *   *   *   *     *         *"
	.STRINGZ "*         *     *   *   *   *     *         *"
	.STRINGZ "*   * * * * * * *   * * *   * * * * * * *   *"
	.STRINGZ "*   *     *           U           *     *   *"
	.STRINGZ "*   *     *   * * * *   * * * *   *     *   *"
	.STRINGZ "*   * * * *   * * * *   * * * *   * * * *   *"
	.STRINGZ "*                     U                     *"
	.STRINGZ "*   * * * * * * * * *   * * * * * * * * *   *"
	.STRINGZ "*   *               *   *               *   *"
	.STRINGZ "*   * * * * * * * * *   * * * * * * * * *   *"
	.STRINGZ "*                     U                     *"
	.STRINGZ "*   * * * *   * * * *   * * * *   * * * *   *"
	.STRINGZ "*   *     *   * * * *   * * * *   *     *   *"
	.STRINGZ "*   *     *     o     U           *     *   *"
	.STRINGZ "*   * * * * * * *   * * *   * * * * * * *   *"
	.STRINGZ "*         *     *   *   *   *     *         *"
	.STRINGZ "*         *     *   *   *   *     *         *"
	.STRINGZ "*         * * * *   * * *   * * * *         *"
	.STRINGZ "*   U                                       *"
	.STRINGZ "* * * * * * * * * * * * * * * * * * * * * * *"
	
	.STRINGZ "* * * * * * * * * * * * * * * * * * * * * * *"
	.STRINGZ "*                                     U     *"
	.STRINGZ "*         * * * *   * * *   * * * *         *"
	.STRINGZ "*         *     *   *   *   *     *         *"
	.STRINGZ "*         *     *   *   *   *     *         *"
	.STRINGZ "*   * * * * * * *   * * *   * * * * * * *   *"
	.STRINGZ "*   *     *         U             *     *   *"
	.STRINGZ "*   *     *   * * * *   * * * *   *     *   *"
	.STRINGZ "*   * * * *   * * * *   * * * *   * * * *   *"
	.STRINGZ "*                   U                       *"
	.STRINGZ "*   * * * * * * * * *   * * * * * * * * *   *"
	.STRINGZ "*   *               *   *               *   *"
	.STRINGZ "*   * * * * * * * * *   * * * * * * * * *   *"
	.STRINGZ "*                       U                   *"
	.STRINGZ "*   * * * *   * * * *   * * * *   * * * *   *"
	.STRINGZ "*   *     *   * * * *   * * * *   *     *   *"
	.STRINGZ "*   *     *     o       U         *     *   *"
	.STRINGZ "*   * * * * * * *   * * *   * * * * * * *   *"
	.STRINGZ "*         *     *   *   *   *     *         *"
	.STRINGZ "*         *     *   *   *   *     *         *"
	.STRINGZ "*         * * * *   * * *   * * * *         *"
	.STRINGZ "*     U                                     *"
	.STRINGZ "* * * * * * * * * * * * * * * * * * * * * * *"
	
	.STRINGZ "* * * * * * * * * * * * * * * * * * * * * * *"
	.STRINGZ "*                                   U       *"
	.STRINGZ "*         * * * *   * * *   * * * *         *"
	.STRINGZ "*         *     *   *   *   *     *         *"
	.STRINGZ "*         *     *   *   *   *     *         *"
	.STRINGZ "*   * * * * * * *   * * *   * * * * * * *   *"
	.STRINGZ "*   *     *       U               *     *   *"
	.STRINGZ "*   *     *   * * * *   * * * *   *     *   *"
	.STRINGZ "*   * * * *   * * * *   * * * *   * * * *   *"
	.STRINGZ "*                 U                         *"
	.STRINGZ "*   * * * * * * * * *   * * * * * * * * *   *"
	.STRINGZ "*   *               *   *               *   *"
	.STRINGZ "*   * * * * * * * * *   * * * * * * * * *   *"
	.STRINGZ "*                         U                 *"
	.STRINGZ "*   * * * *   * * * *   * * * *   * * * *   *"
	.STRINGZ "*   *     *   * * * *   * * * *   *     *   *"
	.STRINGZ "*   *     *     o         U       *     *   *"
	.STRINGZ "*   * * * * * * *   * * *   * * * * * * *   *"
	.STRINGZ "*         *     *   *   *   *     *         *"
	.STRINGZ "*         *     *   *   *   *     *         *"
	.STRINGZ "*         * * * *   * * *   * * * *         *"
	.STRINGZ "*       U                                   *"
	.STRINGZ "* * * * * * * * * * * * * * * * * * * * * * *"
	
	.STRINGZ "* * * * * * * * * * * * * * * * * * * * * * *"
	.STRINGZ "*                                 U         *"
	.STRINGZ "*         * * * *   * * *   * * * *         *"
	.STRINGZ "*         *     *   *   *   *     *         *"
	.STRINGZ "*         *     *   *   *   *     *         *"
	.STRINGZ "*   * * * * * * *   * * *   * * * * * * *   *"
	.STRINGZ "*   *     *     U                 *     *   *"
	.STRINGZ "*   *     *   * * * *   * * * *   *     *   *"
	.STRINGZ "*   * * * *   * * * *   * * * *   * * * *   *"
	.STRINGZ "*               U                           *"
	.STRINGZ "*   * * * * * * * * *   * * * * * * * * *   *"
	.STRINGZ "*   *               *   *               *   *"
	.STRINGZ "*   * * * * * * * * *   * * * * * * * * *   *"
	.STRINGZ "*                           U               *"
	.STRINGZ "*   * * * *   * * * *   * * * *   * * * *   *"
	.STRINGZ "*   *     *   * * * *   * * * *   *     *   *"
	.STRINGZ "*   *     *     o           U     *     *   *"
	.STRINGZ "*   * * * * * * *   * * *   * * * * * * *   *"
	.STRINGZ "*         *     *   *   *   *     *         *"
	.STRINGZ "*         *     *   *   *   *     *         *"
	.STRINGZ "*         * * * *   * * *   * * * *         *"
	.STRINGZ "*         U                                 *"
	.STRINGZ "* * * * * * * * * * * * * * * * * * * * * * *"
	
	.STRINGZ "* * * * * * * * * * * * * * * * * * * * * * *"
	.STRINGZ "*                               U           *"
	.STRINGZ "*         * * * *   * * *   * * * *         *"
	.STRINGZ "*         *     *   *   *   *     *         *"
	.STRINGZ "*         *     *   *   *   *     *         *"
	.STRINGZ "*   * * * * * * *   * * *   * * * * * * *   *"
	.STRINGZ "*   *     *   U                   *     *   *"
	.STRINGZ "*   *     *   * * * *   * * * *   *     *   *"
	.STRINGZ "*   * * * *   * * * *   * * * *   * * * *   *"
	.STRINGZ "*             U                             *"
	.STRINGZ "*   * * * * * * * * *   * * * * * * * * *   *"
	.STRINGZ "*   *               *   *               *   *"
	.STRINGZ "*   * * * * * * * * *   * * * * * * * * *   *"
	.STRINGZ "*                             U             *"
	.STRINGZ "*   * * * *   * * * *   * * * *   * * * *   *"
	.STRINGZ "*   *     *   * * * *   * * * *   *     *   *"
	.STRINGZ "*   *     *     o             U   *     *   *"
	.STRINGZ "*   * * * * * * *   * * *   * * * * * * *   *"
	.STRINGZ "*         *     *   *   *   *     *         *"
	.STRINGZ "*         *     *   *   *   *     *         *"
	.STRINGZ "*         * * * *   * * *   * * * *         *"
	.STRINGZ "*           U                               *"
	.STRINGZ "* * * * * * * * * * * * * * * * * * * * * * *"
	
	.STRINGZ "* * * * * * * * * * * * * * * * * * * * * * *"
	.STRINGZ "*                             U             *"
	.STRINGZ "*         * * * *   * * *   * * * *         *"
	.STRINGZ "*         *     *   *   *   *     *         *"
	.STRINGZ "*         *     *   *   *   *     *         *"
	.STRINGZ "*   * * * * * * *   * * *   * * * * * * *   *"
	.STRINGZ "*   *     * U                     *     *   *"
	.STRINGZ "*   *     *   * * * *   * * * *   *     *   *"
	.STRINGZ "*   * * * *   * * * *   * * * *   * * * *   *"
	.STRINGZ "*           U                               *"
	.STRINGZ "*   * * * * * * * * *   * * * * * * * * *   *"
	.STRINGZ "*   *               *   *               *   *"
	.STRINGZ "*   * * * * * * * * *   * * * * * * * * *   *"
	.STRINGZ "*                               U           *"
	.STRINGZ "*   * * * *   * * * *   * * * *   * * * *   *"
	.STRINGZ "*   *     *   * * * *   * * * *   *     *   *"
	.STRINGZ "*   *     *     o               U *     *   *"
	.STRINGZ "*   * * * * * * *   * * *   * * * * * * *   *"
	.STRINGZ "*         *     *   *   *   *     *         *"
	.STRINGZ "*         *     *   *   *   *     *         *"
	.STRINGZ "*         * * * *   * * *   * * * *         *"
	.STRINGZ "*             U                             *"
	.STRINGZ "* * * * * * * * * * * * * * * * * * * * * * *"
	
	.STRINGZ "* * * * * * * * * * * * * * * * * * * * * * *"
	.STRINGZ "*                           U               *"
	.STRINGZ "*         * * * *   * * *   * * * *         *"
	.STRINGZ "*         *     *   *   *   *     *         *"
	.STRINGZ "*         *     *   *   *   *     *         *"
	.STRINGZ "*   * * * * * * *   * * *   * * * * * * *   *"
	.STRINGZ "*   *     *                       *     *   *"
	.STRINGZ "*   *     * U * * * *   * * * *   *     *   *"
	.STRINGZ "*   * * * *   * * * *   * * * *   * * * *   *"
	.STRINGZ "*         U                                 *"
	.STRINGZ "*   * * * * * * * * *   * * * * * * * * *   *"
	.STRINGZ "*   *               *   *               *   *"
	.STRINGZ "*   * * * * * * * * *   * * * * * * * * *   *"
	.STRINGZ "*                                 U         *"
	.STRINGZ "*   * * * *   * * * *   * * * *   * * * *   *"
	.STRINGZ "*   *     *   * * * *   * * * * U *     *   *"
	.STRINGZ "*   *     *     o                 *     *   *"
	.STRINGZ "*   * * * * * * *   * * *   * * * * * * *   *"
	.STRINGZ "*         *     *   *   *   *     *         *"
	.STRINGZ "*         *     *   *   *   *     *         *"
	.STRINGZ "*         * * * *   * * *   * * * *         *"
	.STRINGZ "*               U                           *"
	.STRINGZ "* * * * * * * * * * * * * * * * * * * * * * *"
	
	.STRINGZ "* * * * * * * * * * * * * * * * * * * * * * *"
	.STRINGZ "*                         U                 *"
	.STRINGZ "*         * * * *   * * *   * * * *         *"
	.STRINGZ "*         *     *   *   *   *     *         *"
	.STRINGZ "*         *     *   *   *   *     *         *"
	.STRINGZ "*   * * * * * * *   * * *   * * * * * * *   *"
	.STRINGZ "*   *     *                       *     *   *"
	.STRINGZ "*   *     *   * * * *   * * * *   *     *   *"
	.STRINGZ "*   * * * * U * * * *   * * * *   * * * *   *"
	.STRINGZ "*       U                                   *"
	.STRINGZ "*   * * * * * * * * *   * * * * * * * * *   *"
	.STRINGZ "*   *               *   *               *   *"
	.STRINGZ "*   * * * * * * * * *   * * * * * * * * *   *"
	.STRINGZ "*                                   U       *"
	.STRINGZ "*   * * * *   * * * *   * * * * U * * * *   *"
	.STRINGZ "*   *     *   * * * *   * * * *   *     *   *"
	.STRINGZ "*   *     *     o                 *     *   *"
	.STRINGZ "*   * * * * * * *   * * *   * * * * * * *   *"
	.STRINGZ "*         *     *   *   *   *     *         *"
	.STRINGZ "*         *     *   *   *   *     *         *"
	.STRINGZ "*         * * * *   * * *   * * * *         *"
	.STRINGZ "*                 U                         *"
	.STRINGZ "* * * * * * * * * * * * * * * * * * * * * * *"
	
	.STRINGZ "* * * * * * * * * * * * * * * * * * * * * * *"
	.STRINGZ "*                       U                   *"
	.STRINGZ "*         * * * *   * * *   * * * *         *"
	.STRINGZ "*         *     *   *   *   *     *         *"
	.STRINGZ "*         *     *   *   *   *     *         *"
	.STRINGZ "*   * * * * * * *   * * *   * * * * * * *   *"
	.STRINGZ "*   *     *                       *     *   *"
	.STRINGZ "*   *     *   * * * *   * * * *   *     *   *"
	.STRINGZ "*   * * * *   * * * *   * * * *   * * * *   *"
	.STRINGZ "*     U     U                               *"
	.STRINGZ "*   * * * * * * * * *   * * * * * * * * *   *"
	.STRINGZ "*   *               *   *               *   *"
	.STRINGZ "*   * * * * * * * * *   * * * * * * * * *   *"
	.STRINGZ "*                               U     U     *"
	.STRINGZ "*   * * * *   * * * *   * * * *   * * * *   *"
	.STRINGZ "*   *     *   * * * *   * * * *   *     *   *"
	.STRINGZ "*   *     *     o                 *     *   *"
	.STRINGZ "*   * * * * * * *   * * *   * * * * * * *   *"
	.STRINGZ "*         *     *   *   *   *     *         *"
	.STRINGZ "*         *     *   *   *   *     *         *"
	.STRINGZ "*         * * * *   * * *   * * * *         *"
	.STRINGZ "*                   U                       *"
	.STRINGZ "* * * * * * * * * * * * * * * * * * * * * * *"
	
	.STRINGZ "* * * * * * * * * * * * * * * * * * * * * * *"
	.STRINGZ "*                     U                     *"
	.STRINGZ "*         * * * *   * * *   * * * *         *"
	.STRINGZ "*         *     *   *   *   *     *         *"
	.STRINGZ "*         *     *   *   *   *     *         *"
	.STRINGZ "*   * * * * * * *   * * *   * * * * * * *   *"
	.STRINGZ "*   *     *                       *     *   *"
	.STRINGZ "*   *     *   * * * *   * * * *   *     *   *"
	.STRINGZ "*   * * * *   * * * *   * * * *   * * * *   *"
	.STRINGZ "*   U         U                             *"
	.STRINGZ "*   * * * * * * * * *   * * * * * * * * *   *"
	.STRINGZ "*   *               *   *               *   *"
	.STRINGZ "*   * * * * * * * * *   * * * * * * * * *   *"
	.STRINGZ "*                             U         U   *"
	.STRINGZ "*   * * * *   * * * *   * * * *   * * * *   *"
	.STRINGZ "*   *     *   * * * *   * * * *   *     *   *"
	.STRINGZ "*   *     *     o                 *     *   *"
	.STRINGZ "*   * * * * * * *   * * *   * * * * * * *   *"
	.STRINGZ "*         *     *   *   *   *     *         *"
	.STRINGZ "*         *     *   *   *   *     *         *"
	.STRINGZ "*         * * * *   * * *   * * * *         *"
	.STRINGZ "*                     U                     *"
	.STRINGZ "* * * * * * * * * * * * * * * * * * * * * * *"
	
	.STRINGZ "* * * * * * * * * * * * * * * * * * * * * * *"
	.STRINGZ "*                   U                       *"
	.STRINGZ "*         * * * *   * * *   * * * *         *"
	.STRINGZ "*         *     *   *   *   *     *         *"
	.STRINGZ "*         *     *   *   *   *     *         *"
	.STRINGZ "*   * * * * * * *   * * *   * * * * * * *   *"
	.STRINGZ "*   *     *                       *     *   *"
	.STRINGZ "*   *     *   * * * *   * * * *   *     *   *"
	.STRINGZ "*   * * * *   * * * *   * * * *   * * * *   *"
	.STRINGZ "* U             U                           *"
	.STRINGZ "*   * * * * * * * * *   * * * * * * * * *   *"
	.STRINGZ "*   *               *   *               *   *"
	.STRINGZ "*   * * * * * * * * *   * * * * * * * * *   *"
	.STRINGZ "*                           U             U *"
	.STRINGZ "*   * * * *   * * * *   * * * *   * * * *   *"
	.STRINGZ "*   *     *   * * * *   * * * *   *     *   *"
	.STRINGZ "*   *     *     o                 *     *   *"
	.STRINGZ "*   * * * * * * *   * * *   * * * * * * *   *"
	.STRINGZ "*         *     *   *   *   *     *         *"
	.STRINGZ "*         *     *   *   *   *     *         *"
	.STRINGZ "*         * * * *   * * *   * * * *         *"
	.STRINGZ "*                       U                   *"
	.STRINGZ "* * * * * * * * * * * * * * * * * * * * * * *"
	
	.STRINGZ "* * * * * * * * * * * * * * * * * * * * * * *"
	.STRINGZ "*                 U                         *"
	.STRINGZ "*         * * * *   * * *   * * * *         *"
	.STRINGZ "*         *     *   *   *   *     *         *"
	.STRINGZ "*         *     *   *   *   *     *         *"
	.STRINGZ "*   * * * * * * *   * * *   * * * * * * *   *"
	.STRINGZ "*   *     *                       *     *   *"
	.STRINGZ "*   *     *   * * * *   * * * *   *     *   *"
	.STRINGZ "*   * * * *   * * * *   * * * *   * * * *   *"
	.STRINGZ "*                 U                         *"
	.STRINGZ "* U * * * * * * * * *   * * * * * * * * *   *"
	.STRINGZ "*   *               *   *               *   *"
	.STRINGZ "*   * * * * * * * * *   * * * * * * * * * U *"
	.STRINGZ "*                         U                 *"
	.STRINGZ "*   * * * *   * * * *   * * * *   * * * *   *"
	.STRINGZ "*   *     *   * * * *   * * * *   *     *   *"
	.STRINGZ "*   *     *     o                 *     *   *"
	.STRINGZ "*   * * * * * * *   * * *   * * * * * * *   *"
	.STRINGZ "*         *     *   *   *   *     *         *"
	.STRINGZ "*         *     *   *   *   *     *         *"
	.STRINGZ "*         * * * *   * * *   * * * *         *"
	.STRINGZ "*                         U                 *"
	.STRINGZ "* * * * * * * * * * * * * * * * * * * * * * *"
	
	.STRINGZ "* * * * * * * * * * * * * * * * * * * * * * *"
	.STRINGZ "*                                           *"
	.STRINGZ "*         * * * * U * * *   * * * *         *"
	.STRINGZ "*         *     *   *   *   *     *         *"
	.STRINGZ "*         *     *   *   *   *     *         *"
	.STRINGZ "*   * * * * * * *   * * *   * * * * * * *   *"
	.STRINGZ "*   *     *                       *     *   *"
	.STRINGZ "*   *     *   * * * *   * * * *   *     *   *"
	.STRINGZ "*   * * * *   * * * *   * * * *   * * * *   *"
	.STRINGZ "*                   U                       *"
	.STRINGZ "*   * * * * * * * * *   * * * * * * * * *   *"
	.STRINGZ "* U *               *   *               * U *"
	.STRINGZ "*   * * * * * * * * *   * * * * * * * * *   *"
	.STRINGZ "*                       U                   *"
	.STRINGZ "*   * * * *   * * * *   * * * *   * * * *   *"
	.STRINGZ "*   *     *   * * * *   * * * *   *     *   *"
	.STRINGZ "*   *     *     o                 *     *   *"
	.STRINGZ "*   * * * * * * *   * * *   * * * * * * *   *"
	.STRINGZ "*         *     *   *   *   *     *         *"
	.STRINGZ "*         *     *   *   *   *     *         *"
	.STRINGZ "*         * * * *   * * * U * * * *         *"
	.STRINGZ "*                                           *"
	.STRINGZ "* * * * * * * * * * * * * * * * * * * * * * *"
	
	.STRINGZ "* * * * * * * * * * * * * * * * * * * * * * *"
	.STRINGZ "*                                           *"
	.STRINGZ "*         * * * *   * * *   * * * *         *"
	.STRINGZ "*         *     * U *   *   *     *         *"
	.STRINGZ "*         *     *   *   *   *     *         *"
	.STRINGZ "*   * * * * * * *   * * *   * * * * * * *   *"
	.STRINGZ "*   *     *                       *     *   *"
	.STRINGZ "*   *     *   * * * *   * * * *   *     *   *"
	.STRINGZ "*   * * * *   * * * *   * * * *   * * * *   *"
	.STRINGZ "*                     U                     *"
	.STRINGZ "*   * * * * * * * * *   * * * * * * * * * U *"
	.STRINGZ "*   *               *   *               *   *"
	.STRINGZ "* U * * * * * * * * *   * * * * * * * * *   *"
	.STRINGZ "*                     U                     *"
	.STRINGZ "*   * * * *   * * * *   * * * *   * * * *   *"
	.STRINGZ "*   *     *   * * * *   * * * *   *     *   *"
	.STRINGZ "*   *     *     o                 *     *   *"
	.STRINGZ "*   * * * * * * *   * * *   * * * * * * *   *"
	.STRINGZ "*         *     *   *   *   *     *         *"
	.STRINGZ "*         *     *   *   * U *     *         *"
	.STRINGZ "*         * * * *   * * *   * * * *         *"
	.STRINGZ "*                                           *"
	.STRINGZ "* * * * * * * * * * * * * * * * * * * * * * *"
	
	.STRINGZ "* * * * * * * * * * * * * * * * * * * * * * *"
	.STRINGZ "*                                           *"
	.STRINGZ "*         * * * *   * * *   * * * *         *"
	.STRINGZ "*         *     *   *   *   *     *         *"
	.STRINGZ "*         *     * U *   *   *     *         *"
	.STRINGZ "*   * * * * * * *   * * *   * * * * * * *   *"
	.STRINGZ "*   *     *                       *     *   *"
	.STRINGZ "*   *     *   * * * *   * * * *   *     *   *"
	.STRINGZ "*   * * * *   * * * *   * * * *   * * * *   *"
	.STRINGZ "*                       U                 U *"
	.STRINGZ "*   * * * * * * * * *   * * * * * * * * *   *"
	.STRINGZ "*   *               *   *               *   *"
	.STRINGZ "*   * * * * * * * * *   * * * * * * * * *   *"
	.STRINGZ "* U                 U                       *"
	.STRINGZ "*   * * * *   * * * *   * * * *   * * * *   *"
	.STRINGZ "*   *     *   * * * *   * * * *   *     *   *"
	.STRINGZ "*   *     *     o                 *     *   *"
	.STRINGZ "*   * * * * * * *   * * *   * * * * * * *   *"
	.STRINGZ "*         *     *   *   * U *     *         *"
	.STRINGZ "*         *     *   *   *   *     *         *"
	.STRINGZ "*         * * * *   * * *   * * * *         *"
	.STRINGZ "*                                           *"
	.STRINGZ "* * * * * * * * * * * * * * * * * * * * * * *"
	
	.STRINGZ "* * * * * * * * * * * * * * * * * * * * * * *"
	.STRINGZ "*                                           *"
	.STRINGZ "*         * * * *   * * *   * * * *         *"
	.STRINGZ "*         *     *   *   *   *     *         *"
	.STRINGZ "*         *     *   *   *   *     *         *"
	.STRINGZ "*   * * * * * * * U * * *   * * * * * * *   *"
	.STRINGZ "*   *     *                       *     *   *"
	.STRINGZ "*   *     *   * * * *   * * * *   *     *   *"
	.STRINGZ "*   * * * *   * * * *   * * * *   * * * * U *"
	.STRINGZ "*                         U                 *"
	.STRINGZ "*   * * * * * * * * *   * * * * * * * * *   *"
	.STRINGZ "*   *               *   *               *   *"
	.STRINGZ "*   * * * * * * * * *   * * * * * * * * *   *"
	.STRINGZ "*                 U                         *"
	.STRINGZ "* U * * * *   * * * *   * * * *   * * * *   *"
	.STRINGZ "*   *     *   * * * *   * * * *   *     *   *"
	.STRINGZ "*   *     *     o                 *     *   *"
	.STRINGZ "*   * * * * * * *   * * * U * * * * * * *   *"
	.STRINGZ "*         *     *   *   *   *     *         *"
	.STRINGZ "*         *     *   *   *   *     *         *"
	.STRINGZ "*         * * * *   * * *   * * * *         *"
	.STRINGZ "*                                           *"
	.STRINGZ "* * * * * * * * * * * * * * * * * * * * * * *"
	
	.STRINGZ "* * * * * * * * * * * * * * * * * * * * * * *"
	.STRINGZ "*                                           *"
	.STRINGZ "*         * * * *   * * *   * * * *         *"
	.STRINGZ "*         *     *   *   *   *     *         *"
	.STRINGZ "*         *     *   *   *   *     *         *"
	.STRINGZ "*   * * * * * * *   * * *   * * * * * * *   *"
	.STRINGZ "*   *     *       U               *     *   *"
	.STRINGZ "*   *     *   * * * *   * * * *   *     * U *"
	.STRINGZ "*   * * * *   * * * *   * * * *   * * * *   *"
	.STRINGZ "*                           U               *"
	.STRINGZ "*   * * * * * * * * *   * * * * * * * * *   *"
	.STRINGZ "*   *               *   *               *   *"
	.STRINGZ "*   * * * * * * * * *   * * * * * * * * *   *"
	.STRINGZ "*               U                           *"
	.STRINGZ "*   * * * *   * * * *   * * * *   * * * *   *"
	.STRINGZ "* U *     *   * * * *   * * * *   *     *   *"
	.STRINGZ "*   *     *     o         U       *     *   *"
	.STRINGZ "*   * * * * * * *   * * *   * * * * * * *   *"
	.STRINGZ "*         *     *   *   *   *     *         *"
	.STRINGZ "*         *     *   *   *   *     *         *"
	.STRINGZ "*         * * * *   * * *   * * * *         *"
	.STRINGZ "*                                           *"
	.STRINGZ "* * * * * * * * * * * * * * * * * * * * * * *"
	
	.STRINGZ "* * * * * * * * * * * * * * * * * * * * * * *"
	.STRINGZ "*                                           *"
	.STRINGZ "*         * * * *   * * *   * * * *         *"
	.STRINGZ "*         *     *   *   *   *     *         *"
	.STRINGZ "*         *     *   *   *   *     *         *"
	.STRINGZ "*   * * * * * * *   * * *   * * * * * * *   *"
	.STRINGZ "*   *     *         U             *     * U *"
	.STRINGZ "*   *     *   * * * *   * * * *   *     *   *"
	.STRINGZ "*   * * * *   * * * *   * * * *   * * * *   *"
	.STRINGZ "*                             U             *"
	.STRINGZ "*   * * * * * * * * *   * * * * * * * * *   *"
	.STRINGZ "*   *               *   *               *   *"
	.STRINGZ "*   * * * * * * * * *   * * * * * * * * *   *"
	.STRINGZ "*             U                             *"
	.STRINGZ "*   * * * *   * * * *   * * * *   * * * *   *"
	.STRINGZ "*   *     *   * * * *   * * * *   *     *   *"
	.STRINGZ "* U *     *     o       U         *     *   *"
	.STRINGZ "*   * * * * * * *   * * *   * * * * * * *   *"
	.STRINGZ "*         *     *   *   *   *     *         *"
	.STRINGZ "*         *     *   *   *   *     *         *"
	.STRINGZ "*         * * * *   * * *   * * * *         *"
	.STRINGZ "*                                           *"
	.STRINGZ "* * * * * * * * * * * * * * * * * * * * * * *"
	
	.STRINGZ "* * * * * * * * * * * * * * * * * * * * * * *"
	.STRINGZ "*                                           *"
	.STRINGZ "*         * * * *   * * *   * * * *         *"
	.STRINGZ "*         *     *   *   *   *     *         *"
	.STRINGZ "*         *     *   *   *   *     *         *"
	.STRINGZ "*   * * * * * * *   * * *   * * * * * * * U *"
	.STRINGZ "*   *     *           U           *     *   *"
	.STRINGZ "*   *     *   * * * *   * * * *   *     *   *"
	.STRINGZ "*   * * * *   * * * *   * * * *   * * * *   *"
	.STRINGZ "*                           U               *"
	.STRINGZ "*   * * * * * * * * *   * * * * * * * * *   *"
	.STRINGZ "*   *               *   *               *   *"
	.STRINGZ "*   * * * * * * * * *   * * * * * * * * *   *"
	.STRINGZ "*               U                           *"
	.STRINGZ "*   * * * *   * * * *   * * * *   * * * *   *"
	.STRINGZ "*   *     *   * * * *   * * * *   *     *   *"
	.STRINGZ "*   *     *     o     U           *     *   *"
	.STRINGZ "* U * * * * * * *   * * *   * * * * * * *   *"
	.STRINGZ "*         *     *   *   *   *     *         *"
	.STRINGZ "*         *     *   *   *   *     *         *"
	.STRINGZ "*         * * * *   * * *   * * * *         *"
	.STRINGZ "*                                           *"
	.STRINGZ "* * * * * * * * * * * * * * * * * * * * * * *"
	
	.STRINGZ "* * * * * * * * * * * * * * * * * * * * * * *"
	.STRINGZ "*                                           *"
	.STRINGZ "*         * * * *   * * *   * * * *         *"
	.STRINGZ "*         *     *   *   *   *     *         *"
	.STRINGZ "*         *     *   *   *   *     *       U *"
	.STRINGZ "*   * * * * * * *   * * *   * * * * * * *   *"
	.STRINGZ "*   *     *                       *     *   *"
	.STRINGZ "*   *     *   * * * * U * * * *   *     *   *"
	.STRINGZ "*   * * * *   * * * *   * * * *   * * * *   *"
	.STRINGZ "*                         U                 *"
	.STRINGZ "*   * * * * * * * * *   * * * * * * * * *   *"
	.STRINGZ "*   *               *   *               *   *"
	.STRINGZ "*   * * * * * * * * *   * * * * * * * * *   *"
	.STRINGZ "*                 U                         *"
	.STRINGZ "*   * * * *   * * * *   * * * *   * * * *   *"
	.STRINGZ "*   *     *   * * * * U * * * *   *     *   *"
	.STRINGZ "*   *     *     o                 *     *   *"
	.STRINGZ "*   * * * * * * *   * * *   * * * * * * *   *"
	.STRINGZ "* U       *     *   *   *   *     *         *"
	.STRINGZ "*         *     *   *   *   *     *         *"
	.STRINGZ "*         * * * *   * * *   * * * *         *"
	.STRINGZ "*                                           *"
	.STRINGZ "* * * * * * * * * * * * * * * * * * * * * * *"
	
	.STRINGZ "* * * * * * * * * * * * * * * * * * * * * * *"
	.STRINGZ "*                                           *"
	.STRINGZ "*         * * * *   * * *   * * * *         *"
	.STRINGZ "*         *     *   *   *   *     *       U *"
	.STRINGZ "*         *     *   *   *   *     *         *"
	.STRINGZ "*   * * * * * * *   * * *   * * * * * * *   *"
	.STRINGZ "*   *     *                       *     *   *"
	.STRINGZ "*   *     *   * * * *   * * * *   *     *   *"
	.STRINGZ "*   * * * *   * * * * U * * * *   * * * *   *"
	.STRINGZ "*                       U                   *"
	.STRINGZ "*   * * * * * * * * *   * * * * * * * * *   *"
	.STRINGZ "*   *               *   *               *   *"
	.STRINGZ "*   * * * * * * * * *   * * * * * * * * *   *"
	.STRINGZ "*                   U                       *"
	.STRINGZ "*   * * * *   * * * * U * * * *   * * * *   *"
	.STRINGZ "*   *     *   * * * *   * * * *   *     *   *"
	.STRINGZ "*   *     *     o                 *     *   *"
	.STRINGZ "*   * * * * * * *   * * *   * * * * * * *   *"
	.STRINGZ "*         *     *   *   *   *     *         *"
	.STRINGZ "* U       *     *   *   *   *     *         *"
	.STRINGZ "*         * * * *   * * *   * * * *         *"
	.STRINGZ "*                                           *"
	.STRINGZ "* * * * * * * * * * * * * * * * * * * * * * *"
	
	.STRINGZ "* * * * * * * * * * * * * * * * * * * * * * *"
	.STRINGZ "*                                           *"
	.STRINGZ "*         * * * *   * * *   * * * *       U *"
	.STRINGZ "*         *     *   *   *   *     *         *"
	.STRINGZ "*         *     *   *   *   *     *         *"
	.STRINGZ "*   * * * * * * *   * * *   * * * * * * *   *"
	.STRINGZ "*   *     *                       *     *   *"
	.STRINGZ "*   *     *   * * * * U * * * *   *     *   *"
	.STRINGZ "*   * * * *   * * * *   * * * *   * * * *   *"
	.STRINGZ "*                     U                     *"
	.STRINGZ "*   * * * * * * * * *   * * * * * * * * *   *"
	.STRINGZ "*   *               *   *               *   *"
	.STRINGZ "*   * * * * * * * * *   * * * * * * * * *   *"
	.STRINGZ "*                     U                     *"
	.STRINGZ "*   * * * *   * * * *   * * * *   * * * *   *"
	.STRINGZ "*   *     *   * * * * U * * * *   *     *   *"
	.STRINGZ "*   *     *     o                 *     *   *"
	.STRINGZ "*   * * * * * * *   * * *   * * * * * * *   *"
	.STRINGZ "*         *     *   *   *   *     *         *"
	.STRINGZ "*         *     *   *   *   *     *         *"
	.STRINGZ "* U       * * * *   * * *   * * * *         *"
	.STRINGZ "*                                           *"
	.STRINGZ "* * * * * * * * * * * * * * * * * * * * * * *"
	
	.END